### ISSUE TITLE
How to combine/compile course content split across different folders ?  

### ISSUE THREAD

**Issue by mayankwadhwani** [muhamed-didovic/eddown#2]
Hey, 

Can you please share how do you compile the different chapters stored in different folders to be viewed and read through a single entry point ?

**Comment by muhamed-didovic** [comment]
Hi @mayankwadhwani, that option doesn't exist, are you referring to HTML files that are downloaded? If that is the case, maybe I can do something and 'adapt' links of the lessons

**Comment by mayankwadhwani** [comment]
@muhamed-didovic Yes. Also, I see that there are errors sometimes while downloading. Is there a way to implement a retry functionality ? 

Another thing i saw was multiple pages / pdf files were downloaded with the content saying "Please register to see the content" - this could be due to session timeout. Is there a way this can be handled ?

**Comment by muhamed-didovic** [comment]
@mayankwadhwani  I'll see if I can make the 'menu' for navigating the courses.
Regarding errors folder, it should be more debug folder but anyways can you tell me which errors do you get or similar.

For  "Please register to see the content"  question, I added check for each page to see if user is still logged in, try to run it with '-h no' flag so you can see the browser and let me know then :)

**Comment by mayankwadhwani** [comment]
@muhamed-didovic  - Yes I'd rather prefer a menu for navigation as a user. I will log and update the errors here. Thanks
